// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ActividadPractica_05.Models;

public partial class db_turnosContext : DbContext
{
    public db_turnosContext(DbContextOptions<db_turnosContext> options)
        : base(options)
    {
    }

    public virtual DbSet<T_DETALLES_TURNO> T_DETALLES_TURNOs { get; set; }

    public virtual DbSet<T_SERVICIO> T_SERVICIOs { get; set; }

    public virtual DbSet<T_TURNO> T_TURNOs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<T_DETALLES_TURNO>(entity =>
        {
            entity.HasKey(e => new { e.id_turno, e.id_servicio });

            entity.ToTable("T_DETALLES_TURNO");

            entity.Property(e => e.observaciones)
                .HasMaxLength(200)
                .IsUnicode(false);
        });

        modelBuilder.Entity<T_SERVICIO>(entity =>
        {
            entity.ToTable("T_SERVICIOS");

            entity.Property(e => e.id).ValueGeneratedNever();
            entity.Property(e => e.enPromocion)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.nombre)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<T_TURNO>(entity =>
        {
            entity.ToTable("T_TURNOS");
            entity.HasKey(e => e.id);

            entity.Property(e => e.cliente)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.fecha)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.hora)
                .HasMaxLength(5)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}