// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ActividadPractica_05.Models;

public partial class T_DETALLES_TURNO
{
    public int id_turno { get; set; }

    public int id_servicio { get; set; }

    public string observaciones { get; set; }
}