// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ActividadPractica_05.Models;

public partial class T_SERVICIO
{
    public int id { get; set; }

    public string nombre { get; set; }

    public int costo { get; set; }

    public string enPromocion { get; set; }
}