// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ActividadPractica_05.Models;

public partial class T_TURNO
{
    public int id { get; set; }

    public string fecha { get; set; }

    public string hora { get; set; }

    public string cliente { get; set; }
    public List<T_DETALLES_TURNO> Detalles { get; set; }

}